### ISSUE TITLE
Cannot read properties of undefined (reading 'getData')

### ISSUE THREAD

**Issue by AidanWright** [Fabrizz/MMM-OnSpotify#22]
Hi, I installed MMM-OnSpotify to a fresh install of MM2 per the instructions in the readme. I followed the instructions to run the Authentication Service and the mirror is able to display my username and premium status, but is unable to display the current song.

 
<img width="1440" alt="Screenshot 2023-08-01 at 11 37 05 AM" src="https://github.com/Fabrizz/MMM-OnSpotify/assets/38870143/3afbb612-2364-4605-adce-1cfc2773d611">

I get the following in the server's logs:
 
```
[01.08.2023 11:25.42.077] [LOG]   TypeError: Cannot read properties of undefined (reading 'getData')
    at Class.fetchSpotifyData (/home/pi/MagicMirror/modules/MMM-OnSpotify/node_helper.js:52:37)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-OnSpotify/node_helper.js:33:14)
    at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:104:11)
    at Socket.emit (node:events:513:28)
    at Socket.emitUntyped (/home/pi/MagicMirror/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/pi/MagicMirror/node_modules/socket.io/dist/socket.js:703:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

And in the web console:

```
11:37:23.890 Uncaught (in promise) TypeError: progress is null
    updatePlayerData SpotifyDomBuilder.js:398
    smartUpdate MMM-OnSpotify.js:557
    socketNotificationReceived MMM-OnSpotify.js:300
    socket module.js:232
    MMSocket socketclient.js:38
    emit index.mjs:136
    emitEvent socket.js:498
    onevent socket.js:485
    onevent socketclient.js:32
    onpacket socket.js:455
    emit index.mjs:136
    ondecoded manager.js:204
249 SpotifyDomBuilder.js:398:5
```

**Comment by AidanWright** [comment]
I was able to solve the issue. When pasting the module config generated by Authentication Service into the config.js over SSH, part of the accessToken was cut off. Adding the missing text from the token along with a `",` delimiter fixed the issue.
